/**
 * CompressX – type definitions for the image compression workspace.
 *
 * These types describe every piece of state the workspace hook manages,
 * the settings the user can tweak, and the message protocol spoken between
 * the main thread and the compression Web Worker.
 */

// ---------------------------------------------------------------------------
// Compression settings (user-facing controls)
// ---------------------------------------------------------------------------

export type OutputFormat = "webp" | "jpeg" | "png";

export interface CompressionSettings {
  /** Quality 0‒100 (ignored for PNG lossless). Default: 80 */
  quality: number;
  /** Target output format. Default: "webp" */
  format: OutputFormat;
  /** Optional max width in px – null means "no constraint". Default: null */
  maxWidth: number | null;
  /** Optional max height in px – null means "no constraint". Default: null */
  maxHeight: number | null;
  /** When true the aspect ratio is preserved when resizing. Default: true */
  maintainAspectRatio: boolean;
}

/** Sensible defaults so the workspace starts ready-to-go. */
export const DEFAULT_SETTINGS: CompressionSettings = {
  quality: 80,
  format: "webp",
  maxWidth: null,
  maxHeight: null,
  maintainAspectRatio: true,
};

// ---------------------------------------------------------------------------
// Per-image status & item
// ---------------------------------------------------------------------------

export type ImageStatus = "pending" | "compressing" | "done" | "error";

export interface ImageItem {
  /** Unique id – generated by crypto.randomUUID() on add. */
  id: string;
  /** Reference to the original File the user dropped / selected. */
  file: File;
  /** Display-friendly file name. */
  name: string;
  /** Original file size in bytes. */
  originalSize: number;
  /** Original image width in px. */
  originalWidth: number;
  /** Original image height in px. */
  originalHeight: number;
  /** Object URL created via URL.createObjectURL for preview. */
  previewUrl: string;

  /** Compressed blob – null until compression finishes. */
  compressedBlob: Blob | null;
  /** Compressed file size in bytes – 0 until done. */
  compressedSize: number;
  /** Compressed image width – null until done. */
  compressedWidth: number | null;
  /** Compressed image height – null until done. */
  compressedHeight: number | null;
  /** Lifecycle status. */
  status: ImageStatus;
  /** Error message when status === "error". */
  error: string | null;
  /** Percentage of bytes saved (0‒100). 0 when not yet compressed. */
  compressionRatio: number;
}

// ---------------------------------------------------------------------------
// Overall workspace status
// ---------------------------------------------------------------------------

export type WorkspaceStatus = "idle" | "compressing" | "done" | "partial-error";

// ---------------------------------------------------------------------------
// Workspace state (the full slice consumed by the hook)
// ---------------------------------------------------------------------------

export interface WorkspaceState {
  /** Ordered list of image items. */
  images: ImageItem[];
  /** Active compression settings. */
  settings: CompressionSettings;
  /** High-level workspace status – derived from image statuses. */
  workspaceStatus: WorkspaceStatus;
  /** 0‒100 progress across the current batch (fraction of images done). */
  batchProgress: number;
  /** Whether a batch operation is currently running. */
  isBatchRunning: boolean;
}

// ---------------------------------------------------------------------------
// Worker ↔ main-thread message protocol
// ---------------------------------------------------------------------------

/** Discriminated messages sent FROM the main thread TO the worker. */
export type WorkerRequest =
  | { type: "compress"; id: string; fileData: ArrayBuffer; fileName: string; settings: CompressionSettings }
  | { type: "abort"; id: string }
  | { type: "terminate" };

/** Shape returned by the worker after a successful compression. */
export interface CompressionResult {
  id: string;
  compressedData: ArrayBuffer;
  compressedSize: number;
  compressedWidth: number;
  compressedHeight: number;
  mimeType: string;
}

/** Shape returned by the worker on failure. */
export interface CompressionError {
  id: string;
  message: string;
}

/** Discriminated messages sent FROM the worker TO the main thread. */
export type WorkerResponse =
  | { type: "progress"; id: string; progress: number }
  | { type: "done"; payload: CompressionResult }
  | { type: "error"; payload: CompressionError }
  | { type: "ready" };

// ---------------------------------------------------------------------------
// API request / response shapes (used by the worker to talk to the server)
// ---------------------------------------------------------------------------

export interface CompressApiRequest {
  /** Image data as base-64 (data URL). */
  imageData: string;
  fileName: string;
  quality: number;
  format: OutputFormat;
  maxWidth: number | null;
  maxHeight: number | null;
  maintainAspectRatio: boolean;
}

export interface CompressApiResponse {
  /** Base-64 encoded compressed image (data URL). */
  compressedData: string;
  compressedSize: number;
  compressedWidth: number;
  compressedHeight: number;
  mimeType: string;
}
